export interface Stock {
  id: string
  name: string
  symbol: string
  sector: string
  yearlyPerformance: number[] // 10 years of performance data
}

export interface LocalScenario {
  id: string
  country: string
  title: string
  description: string
  impact: {
    economy: number // -5 to 5, negative is bad, positive is good
    stockMarket: number
    realEstate: number
  }
  stocks: Stock[]
  treasuryYield: number // Annual yield for treasury bills
}

function generateYearlyPerformance(): number[] {
  return Array.from({ length: 10 }, () => Math.random() * 0.4 - 0.2) // Random performance between -20% and 20%
}

export const localScenarios: LocalScenario[] = [
  {
    id: "uk-1",
    country: "United Kingdom",
    title: "Brexit Aftermath",
    description: "The UK deals with economic challenges and opportunities following its exit from the European Union.",
    impact: { economy: -2, stockMarket: -1, realEstate: 1 },
    stocks: [
      {
        id: "uk-1",
        name: "HSBC Holdings",
        symbol: "HSBA.L",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      { id: "uk-2", name: "BP", symbol: "BP.L", sector: "Energy", yearlyPerformance: generateYearlyPerformance() },
      {
        id: "uk-3",
        name: "GlaxoSmithKline",
        symbol: "GSK.L",
        sector: "Healthcare",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "uk-4",
        name: "Unilever",
        symbol: "ULVR.L",
        sector: "Consumer Goods",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "uk-5",
        name: "Vodafone Group",
        symbol: "VOD.L",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "uk-6",
        name: "Barclays",
        symbol: "BARC.L",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      { id: "uk-7", name: "Tesco", symbol: "TSCO.L", sector: "Retail", yearlyPerformance: generateYearlyPerformance() },
      {
        id: "uk-8",
        name: "Rio Tinto",
        symbol: "RIO.L",
        sector: "Mining",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "uk-9",
        name: "BT Group",
        symbol: "BT-A.L",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "uk-10",
        name: "Rolls-Royce Holdings",
        symbol: "RR.L",
        sector: "Aerospace",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.03,
  },
  {
    id: "germany-1",
    country: "Germany",
    title: "Green Energy Revolution",
    description: "Germany leads Europe in renewable energy adoption, boosting related industries.",
    impact: { economy: 3, stockMarket: 2, realEstate: 1 },
    stocks: [
      {
        id: "de-1",
        name: "Siemens",
        symbol: "SIE.DE",
        sector: "Industrials",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-2",
        name: "Volkswagen",
        symbol: "VOW3.DE",
        sector: "Automotive",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-3",
        name: "Deutsche Bank",
        symbol: "DBK.DE",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-4",
        name: "SAP",
        symbol: "SAP.DE",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-5",
        name: "Bayer",
        symbol: "BAYN.DE",
        sector: "Healthcare",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-6",
        name: "Allianz",
        symbol: "ALV.DE",
        sector: "Insurance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-7",
        name: "BASF",
        symbol: "BAS.DE",
        sector: "Chemicals",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-8",
        name: "Deutsche Telekom",
        symbol: "DTE.DE",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-9",
        name: "BMW",
        symbol: "BMW.DE",
        sector: "Automotive",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "de-10",
        name: "Adidas",
        symbol: "ADS.DE",
        sector: "Consumer Goods",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.02,
  },
  {
    id: "singapore-1",
    country: "Singapore",
    title: "Fintech Hub Expansion",
    description: "Singapore strengthens its position as Asia's leading fintech hub, attracting global investments.",
    impact: { economy: 4, stockMarket: 3, realEstate: 2 },
    stocks: [
      {
        id: "sg-1",
        name: "DBS Group",
        symbol: "D05.SI",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-2",
        name: "Singtel",
        symbol: "Z74.SI",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-3",
        name: "Grab Holdings",
        symbol: "GRAB",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-4",
        name: "Sea Limited",
        symbol: "SE",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-5",
        name: "CapitaLand",
        symbol: "C31.SI",
        sector: "Real Estate",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-6",
        name: "Keppel Corporation",
        symbol: "BN4.SI",
        sector: "Conglomerate",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-7",
        name: "OCBC Bank",
        symbol: "O39.SI",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-8",
        name: "Wilmar International",
        symbol: "F34.SI",
        sector: "Agribusiness",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-9",
        name: "Singapore Airlines",
        symbol: "C6L.SI",
        sector: "Aviation",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "sg-10",
        name: "Genting Singapore",
        symbol: "G13.SI",
        sector: "Hospitality",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.04,
  },
  {
    id: "us-1",
    country: "United States",
    title: "Tech Sector Boom",
    description: "Silicon Valley experiences unprecedented growth in AI and quantum computing sectors.",
    impact: { economy: 5, stockMarket: 4, realEstate: 3 },
    stocks: [
      {
        id: "us-1",
        name: "Apple",
        symbol: "AAPL",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-2",
        name: "Microsoft",
        symbol: "MSFT",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-3",
        name: "Amazon",
        symbol: "AMZN",
        sector: "E-commerce",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-4",
        name: "Alphabet",
        symbol: "GOOGL",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-5",
        name: "Tesla",
        symbol: "TSLA",
        sector: "Automotive",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-6",
        name: "NVIDIA",
        symbol: "NVDA",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-7",
        name: "JPMorgan Chase",
        symbol: "JPM",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "us-8",
        name: "Johnson & Johnson",
        symbol: "JNJ",
        sector: "Healthcare",
        yearlyPerformance: generateYearlyPerformance(),
      },
      { id: "us-9", name: "Walmart", symbol: "WMT", sector: "Retail", yearlyPerformance: generateYearlyPerformance() },
      { id: "us-10", name: "Visa", symbol: "V", sector: "Finance", yearlyPerformance: generateYearlyPerformance() },
    ],
    treasuryYield: 0.05,
  },
  {
    id: "south-africa-1",
    country: "South Africa",
    title: "Resource Nationalism",
    description: "South Africa implements new policies to retain more value from its mineral resources.",
    impact: { economy: 2, stockMarket: 1, realEstate: 0 },
    stocks: [
      {
        id: "za-1",
        name: "Naspers",
        symbol: "NPN.JO",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-2",
        name: "Anglo American",
        symbol: "AGL.JO",
        sector: "Mining",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-3",
        name: "FirstRand",
        symbol: "FSR.JO",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-4",
        name: "MTN Group",
        symbol: "MTN.JO",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      { id: "za-5", name: "Sasol", symbol: "SOL.JO", sector: "Energy", yearlyPerformance: generateYearlyPerformance() },
      {
        id: "za-6",
        name: "Standard Bank",
        symbol: "SBK.JO",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-7",
        name: "Shoprite",
        symbol: "SHP.JO",
        sector: "Retail",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-8",
        name: "Vodacom",
        symbol: "VOD.JO",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-9",
        name: "Impala Platinum",
        symbol: "IMP.JO",
        sector: "Mining",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "za-10",
        name: "Capitec Bank",
        symbol: "CPI.JO",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.06,
  },
  {
    id: "france-1",
    country: "France",
    title: "Tourism Recovery",
    description: "France sees a strong rebound in tourism, boosting service and luxury goods sectors.",
    impact: { economy: 3, stockMarket: 2, realEstate: 2 },
    stocks: [
      {
        id: "fr-1",
        name: "LVMH",
        symbol: "MC.PA",
        sector: "Luxury Goods",
        yearlyPerformance: generateYearlyPerformance(),
      },
      { id: "fr-2", name: "Total", symbol: "FP.PA", sector: "Energy", yearlyPerformance: generateYearlyPerformance() },
      {
        id: "fr-3",
        name: "Sanofi",
        symbol: "SAN.PA",
        sector: "Healthcare",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "fr-4",
        name: "BNP Paribas",
        symbol: "BNP.PA",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "fr-5",
        name: "Kering",
        symbol: "KER.PA",
        sector: "Luxury Goods",
        yearlyPerformance: generateYearlyPerformance(),
      },
      { id: "fr-6", name: "AXA", symbol: "CS.PA", sector: "Insurance", yearlyPerformance: generateYearlyPerformance() },
      {
        id: "fr-7",
        name: "Airbus",
        symbol: "AIR.PA",
        sector: "Aerospace",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "fr-8",
        name: "L'Oréal",
        symbol: "OR.PA",
        sector: "Consumer Goods",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "fr-9",
        name: "Carrefour",
        symbol: "CA.PA",
        sector: "Retail",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "fr-10",
        name: "Orange",
        symbol: "ORA.PA",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.03,
  },
  {
    id: "russia-1",
    country: "Russia",
    title: "Energy Market Shifts",
    description: "Russia adapts to changing global energy demands, investing in new technologies.",
    impact: { economy: 1, stockMarket: 2, realEstate: 0 },
    stocks: [
      {
        id: "ru-1",
        name: "Gazprom",
        symbol: "GAZP.ME",
        sector: "Energy",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-2",
        name: "Sberbank",
        symbol: "SBER.ME",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-3",
        name: "Lukoil",
        symbol: "LKOH.ME",
        sector: "Energy",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-4",
        name: "Norilsk Nickel",
        symbol: "GMKN.ME",
        sector: "Mining",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-5",
        name: "Rosneft",
        symbol: "ROSN.ME",
        sector: "Energy",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-6",
        name: "Yandex",
        symbol: "YNDX.ME",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-7",
        name: "Magnit",
        symbol: "MGNT.ME",
        sector: "Retail",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-8",
        name: "VTB Bank",
        symbol: "VTBR.ME",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-9",
        name: "Novatek",
        symbol: "NVTK.ME",
        sector: "Energy",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "ru-10",
        name: "Polyus",
        symbol: "PLZL.ME",
        sector: "Mining",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.07,
  },
  {
    id: "japan-1",
    country: "Japan",
    title: "Aging Population Innovations",
    description: "Japan's healthcare and robotics industries boom as they address challenges of an aging population.",
    impact: { economy: 3, stockMarket: 3, realEstate: 1 },
    stocks: [
      {
        id: "jp-1",
        name: "Toyota Motor",
        symbol: "7203.T",
        sector: "Automotive",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-2",
        name: "SoftBank Group",
        symbol: "9984.T",
        sector: "Technology",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-3",
        name: "Sony",
        symbol: "6758.T",
        sector: "Consumer Electronics",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-4",
        name: "Mitsubishi UFJ Financial",
        symbol: "8306.T",
        sector: "Finance",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-5",
        name: "Nintendo",
        symbol: "7974.T",
        sector: "Gaming",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-6",
        name: "Fast Retailing",
        symbol: "9983.T",
        sector: "Retail",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-7",
        name: "Takeda Pharmaceutical",
        symbol: "4502.T",
        sector: "Healthcare",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-8",
        name: "Nippon Telegraph and Telephone",
        symbol: "9432.T",
        sector: "Telecommunications",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-9",
        name: "Honda Motor",
        symbol: "7267.T",
        sector: "Automotive",
        yearlyPerformance: generateYearlyPerformance(),
      },
      {
        id: "jp-10",
        name: "Fanuc",
        symbol: "6954.T",
        sector: "Robotics",
        yearlyPerformance: generateYearlyPerformance(),
      },
    ],
    treasuryYield: 0.02,
  },
]

export const countryColors: { [key: string]: string } = {
  "United Kingdom": "#1e88e5",
  Germany: "#43a047",
  Singapore: "#fb8c00",
  "United States": "#e53935",
  "South Africa": "#8e24aa",
  France: "#3949ab",
  Russia: "#d81b60",
  Japan: "#00acc1",
}

